'use client';

import { Fragment, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AddRounded, ArrowBackRounded, CloseRounded, EmailRounded, GroupsRounded, NotificationsActiveRounded, SearchRounded, TimelineRounded } from '@mui/icons-material';
import { Box, Button, Card, Chip, Divider, Grid, MenuItem, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';

type Rule = { id: number; filter: string; operator: string; value: string };
type Block = { id: number; rules: Rule[] };
const filters = ['Email', 'Email Action', 'Last Emailed', 'Push Notification', 'Push Notification Action', 'Last Push Notification', 'Current Lifecycle Segment', 'Historical Lifecycle Segment', 'Journey Automation', 'Audience Group', 'Country', 'Account Status', 'User Type', 'Created Date'];
const operators: Record<string, string[]> = { 'Email Action': ['Sent', 'Opened', 'Not opened', 'Clicked', 'Not clicked'], 'Push Notification Action': ['Sent', 'Clicked', 'Not clicked'], Country: ['Is', 'Is not'], 'User Type': ['Is', 'Is not'], 'Account Status': ['Is', 'Is not'], 'Current Lifecycle Segment': ['Is', 'Is not'], 'Historical Lifecycle Segment': ['Is', 'Is not'], 'Audience Group': ['Is', 'Is not'], 'Journey Automation': ['Is', 'Is not'], Email: ['Is available', 'Is not available'], 'Push Notification': ['Is available', 'Is not available'], 'Last Emailed': ['In the last', 'More than'], 'Last Push Notification': ['In the last', 'More than'], 'Created Date': ['Is', 'Before', 'After'] };
const values: Record<string, string[]> = { Country: ['Canada', 'United States', 'United Kingdom', 'Australia', 'Germany'], 'User Type': ['Premium', 'Free', 'Trial'], 'Account Status': ['Active', 'Unconfirmed', 'Deleted'], 'Current Lifecycle Segment': ['New users', 'Onboarding complete', 'Paid customers', 'At-risk / inactive'], 'Audience Group': ['At-risk customers', 'Premium subscribers', 'New users · 7 days'], 'Email Action': ['Sent', 'Opened', 'Not opened', 'Clicked', 'Not clicked'], 'Push Notification Action': ['Sent', 'Clicked', 'Not clicked'] };

const makeRule = (id: number): Rule => ({ id, filter: '', operator: '', value: '' });
const makeBlock = (id: number, ruleId: number): Block => ({ id, rules: [makeRule(ruleId)] });

export default function AudienceGroupWorkspace({ groupId }: { groupId: string }) {
  const router = useRouter();
  const title = decodeURIComponent(groupId).replace(/-/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase());
  const [blocks, setBlocks] = useState<Block[]>([makeBlock(1, 1)]);
  const [nextId, setNextId] = useState(2);
  const [query, setQuery] = useState('');
  const conditionCount = blocks.reduce((sum, block) => sum + block.rules.length, 0);
  const updateRule = (blockId: number, ruleId: number, field: keyof Rule, value: string) => setBlocks(current => current.map(block => block.id !== blockId ? block : { ...block, rules: block.rules.map(rule => rule.id !== ruleId ? rule : { ...rule, [field]: value, ...(field === 'filter' ? { operator: '', value: '' } : field === 'operator' ? { value: '' } : {}) }) }));
  const addAnd = (blockId: number) => { if (conditionCount >= 10) return; setBlocks(current => current.map(block => block.id === blockId ? { ...block, rules: [...block.rules, makeRule(nextId)] } : block)); setNextId(value => value + 1); };
  const addOr = () => { if (conditionCount >= 10) return; setBlocks(current => [...current, makeBlock(current.length + 1, nextId)]); setNextId(value => value + 1); };
  const removeRule = (blockId: number, ruleId: number) => setBlocks(current => current.map(block => block.id === blockId ? { ...block, rules: block.rules.filter(rule => rule.id !== ruleId) } : block).filter(block => block.rules.length));
  const users = [{ user: 'customer_123', email: 'customer123@example.com', status: 'Active', location: 'Toronto, Canada', created: '23 Sep 2026, 05:55 pm' }, { user: 'customer_847', email: 'customer847@example.com', status: 'Active', location: 'New York, United States', created: '22 Sep 2026, 10:20 am' }, { user: 'customer_219', email: 'customer219@example.com', status: 'Active', location: 'London, United Kingdom', created: '20 Sep 2026, 04:10 pm' }, { user: 'customer_442', email: 'customer442@example.com', status: 'Unconfirmed', location: 'Berlin, Germany', created: '18 Sep 2026, 09:42 am' }];
  const filteredUsers = users.filter(user => `${user.user} ${user.email}`.toLowerCase().includes(query.toLowerCase()));
  const openUser = (userId: string) => router.push(`/dashboard/users/${userId}`);
  return <Stack gap={2} className="audience-group-workspace">
    <Button startIcon={<ArrowBackRounded />} onClick={() => router.push('/dashboard/users')} className="group-back-button">Back to audience groups</Button>
    <Card className="group-title-card"><Typography color="text.secondary" fontSize={10}>Audience group</Typography><Typography variant="h3">{title}</Typography></Card>
    <Card className="group-section-card"><Typography variant="h3">Group conditions</Typography><Typography color="text.secondary" fontSize={12}>Build the audience using filters for user data, lifecycle, and engagement.</Typography><Stack gap={1.5} sx={{ mt: 2 }}><Box className="condition-groups"><Stack direction="row" justifyContent="space-between" alignItems="flex-start" sx={{ px: 1, pb: 1 }}><Box><Typography fontWeight={900}>Match {blocks.length > 1 ? 'any' : 'all'} of these conditions</Typography><Typography color="text.secondary" fontSize={11}>Conditions joined with <strong>{blocks.length > 1 ? 'OR' : 'AND'}</strong></Typography></Box><Chip label={blocks.length > 1 ? 'OR' : 'AND'} className="condition-logic-chip" size="small" /></Stack>{blocks.map((block, index) => <Fragment key={block.id}><Box className="condition-block"><Stack gap={1.2} className="condition-block-inner">{block.rules.map(rule => <ConditionRow key={rule.id} rule={rule} onChange={(field, value) => updateRule(block.id, rule.id, field, value)} onRemove={() => removeRule(block.id, rule.id)} />)}<Button size="small" startIcon={<AddRounded />} onClick={() => addAnd(block.id)} disabled={conditionCount >= 10} className="condition-add-button">AND</Button></Stack></Box>{index < blocks.length - 1 && <Box className="condition-or-divider"><span>OR</span></Box>}</Fragment>)}<Button size="small" startIcon={<AddRounded />} onClick={addOr} disabled={conditionCount >= 10} className="condition-add-button condition-add-or">OR</Button></Box></Stack><Divider sx={{ my: 2 }} /><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography color="text.secondary" fontSize={12}>{conditionCount} / 10 conditions</Typography><Button variant="contained">Save conditions</Button></Stack></Card>
    <EngagementCard />
    <Card className="group-section-card users-in-group"><Typography variant="h3">Users in this group</Typography><Divider sx={{ mx: -2.5, mt: 2 }} /><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={1.2} sx={{ mt: 2 }}><TextField size="small" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search users by name or email" InputProps={{ startAdornment: <SearchRounded fontSize="small" sx={{ mr: 1, color: '#7c8aa2' }} /> }} /><Typography color="text.secondary" fontSize={11} sx={{ alignSelf: 'center' }}>{filteredUsers.length} users currently match these conditions.</Typography></Stack><Box sx={{ overflowX: 'auto', mt: 1.5 }}><Table size="small"><TableHead><TableRow>{['User', 'Email', 'Status', 'Location', 'Created'].map(label => <TableCell key={label}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{filteredUsers.map(user => <TableRow key={user.user} hover tabIndex={0} className="group-user-row" onClick={() => openUser(user.user)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') openUser(user.user); }}>{<TableCell><Typography fontSize={11} fontWeight={900}>{user.user}</Typography></TableCell>}<TableCell>{user.email}</TableCell><TableCell><Chip label={user.status} size="small" className="active-chip" /></TableCell><TableCell>{user.location}</TableCell><TableCell>{user.created}</TableCell></TableRow>)}</TableBody></Table></Box></Card>
  </Stack>;
}

function ConditionRow({ rule, onChange, onRemove }: { rule: Rule; onChange: (field: keyof Rule, value: string) => void; onRemove: () => void }) {
  const optionValues = values[rule.filter];
  return <Stack direction={{ xs: 'column', md: 'row' }} gap={1} className="condition-row-card"><Select size="small" displayEmpty value={rule.filter} onChange={event => onChange('filter', event.target.value)}><MenuItem value="">Choose a filter</MenuItem>{filters.map(filter => <MenuItem key={filter} value={filter}>{filter}</MenuItem>)}</Select>{rule.filter && <Select size="small" displayEmpty value={rule.operator} onChange={event => onChange('operator', event.target.value)}><MenuItem value="">Choose an operator</MenuItem>{(operators[rule.filter] || ['Is']).map(operator => <MenuItem key={operator} value={operator}>{operator}</MenuItem>)}</Select>}{rule.operator && (optionValues ? <Select size="small" displayEmpty value={rule.value} onChange={event => onChange('value', event.target.value)}><MenuItem value="">Choose a value</MenuItem>{optionValues.map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</Select> : <TextField size="small" placeholder="Enter a value" value={rule.value} onChange={event => onChange('value', event.target.value)} />)}<Button aria-label="Remove condition" onClick={onRemove} className="condition-remove-button"><CloseRounded fontSize="small" /></Button></Stack>;
}

function EngagementCard() { const metric = (Icon: typeof EmailRounded, label: string, value: string) => <Card className="group-metric"><Icon fontSize="small" /><Typography color="text.secondary" fontSize={10}>{label}</Typography><Typography fontSize={18} fontWeight={900}>{value}</Typography></Card>; return <Card className="group-section-card"><Typography variant="h3">Engagement</Typography><Typography color="text.secondary" fontSize={12}>Email and push notification performance for this audience group.</Typography><Grid container spacing={1.2} sx={{ mt: 1 }}>{metric(EmailRounded, 'Emails sent', '0')}{metric(EmailRounded, 'Emails opened', '0')}{metric(GroupsRounded, 'Pushes sent', '0')}{metric(NotificationsActiveRounded, 'Pushes clicked', '0')}</Grid><Grid container spacing={1.5} sx={{ mt: 1 }}><Grid item xs={12} md={6}><Box className="group-engagement-panel"><Typography fontWeight={900}>Email engagement</Typography>{['Open rate|0%', 'Click rate|0%', 'Delivery rate|0%', 'Bounce rate|0%', 'Unsubscribe rate|0%', 'Spam complaint rate|0%'].map(row => <MetricRow key={row} value={row} />)}</Box></Grid><Grid item xs={12} md={6}><Box className="group-engagement-panel"><Typography fontWeight={900}>Push engagement</Typography>{['Sent|0', 'Delivered|0', 'Failed|0', 'Click rate|0%', 'No token|0%'].map(row => <MetricRow key={row} value={row} />)}</Box></Grid></Grid></Card>; }
function MetricRow({ value }: { value: string }) { const [label, amount] = value.split('|'); return <Stack direction="row" justifyContent="space-between" className="group-metric-row"><Typography fontSize={10}>{label}</Typography><Typography fontSize={10} fontWeight={900}>{amount}</Typography></Stack>; }
