'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowBackRounded, EmailRounded, GroupsRounded, NotificationsActiveRounded, SearchRounded } from '@mui/icons-material';
import { Box, Button, Card, Chip, Grid, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';

const segmentData: Record<string, { name: string; description: string; emails: string; opened: string; pushes: string; clicks: string; segmentUsers: string }> = {
  'new-users': { name: 'New users', description: 'Users who joined in the last 7 days', emails: '0', opened: '0', pushes: '0', clicks: '0', segmentUsers: '12,480' },
  'onboarding-complete': { name: 'Onboarding complete', description: 'Completed the core onboarding event', emails: '0', opened: '0', pushes: '1,284', clicks: '82', segmentUsers: '16,204' },
  'paid-customers': { name: 'Paid customers', description: 'Completed a purchase or subscription', emails: '4,208', opened: '1,992', pushes: '3,840', clicks: '412', segmentUsers: '8,421' },
  'at-risk': { name: 'At-risk / inactive', description: 'No meaningful activity in 14 days', emails: '2,108', opened: '284', pushes: '1,008', clicks: '31', segmentUsers: '5,215' },
};

export default function LifecycleSegmentWorkspace({ segmentId }: { segmentId: string }) {
  const router = useRouter();
  const data = segmentData[segmentId] || { name: decodeURIComponent(segmentId).replace(/-/g, ' '), description: 'Automatic lifecycle segment', emails: '0', opened: '0', pushes: '0', clicks: '0', segmentUsers: '0' };
  const [query, setQuery] = useState('');
  const users = [{ id: 'customer_123', name: 'customer_123', email: 'customer123@example.com', status: 'Active', location: 'Toronto, Canada', created: '23 Sep 2026, 05:55 pm' }, { id: 'customer_847', name: 'customer_847', email: 'customer847@example.com', status: 'Active', location: 'New York, United States', created: '22 Sep 2026, 10:20 am' }, { id: 'customer_219', name: 'customer_219', email: 'customer219@example.com', status: 'Active', location: 'London, United Kingdom', created: '20 Sep 2026, 04:10 pm' }, { id: 'customer_442', name: 'customer_442', email: 'customer442@example.com', status: 'Unconfirmed', location: 'Berlin, Germany', created: '18 Sep 2026, 09:42 am' }].filter(user => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase()));
  return <Stack gap={2} className="audience-group-workspace"><Button startIcon={<ArrowBackRounded />} onClick={() => router.push('/dashboard/users')} className="group-back-button">Back to lifecycle segments</Button><Card className="group-title-card"><Typography color="text.secondary" fontSize={10}>Lifecycle segment</Typography><Typography variant="h3">{data.name}</Typography><Typography color="text.secondary" fontSize={11}>{data.description}</Typography></Card><Card className="group-section-card"><Typography variant="h3">Engagement</Typography><Typography color="text.secondary" fontSize={12}>Email and push performance for this lifecycle segment.</Typography><Grid container spacing={1.2} sx={{ mt: 1 }}>{metric(EmailRounded, 'Emails sent', data.emails)}{metric(EmailRounded, 'Emails opened', data.opened)}{metric(GroupsRounded, 'Pushes sent', data.pushes)}{metric(NotificationsActiveRounded, 'Pushes clicked', data.clicks)}</Grid><Grid container spacing={1.5} sx={{ mt: 1 }}><Grid item xs={12} md={6}><Box className="group-engagement-panel"><Typography fontWeight={900}>Email engagement</Typography>{['Open rate|0%', 'Click rate|0%', 'Delivery rate|0%', 'Bounce rate|0%', 'Unsubscribe rate|0%', 'Spam complaint rate|0%'].map(row => <MetricRow key={row} value={row} />)}</Box></Grid><Grid item xs={12} md={6}><Box className="group-engagement-panel"><Typography fontWeight={900}>Push engagement</Typography>{[`Sent|${data.pushes}`, 'Delivered|0', 'Failed|0', 'Click rate|0%', 'No token|0%'].map(row => <MetricRow key={row} value={row} />)}</Box></Grid></Grid></Card><Card className="group-section-card users-in-group"><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'center' }} gap={1}><Box><Typography variant="h3">Users in this segment</Typography><Typography color="text.secondary" fontSize={12}>{data.segmentUsers} users</Typography></Box><TextField size="small" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search users by name or email" InputProps={{ startAdornment: <SearchRounded fontSize="small" sx={{ mr: 1, color: '#7c8aa2' }} /> }} /></Stack><Box sx={{ overflowX: 'auto', mt: 1.5 }}><Table size="small"><TableHead><TableRow>{['User', 'Email', 'Status', 'Location', 'Created'].map(label => <TableCell key={label}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{users.map(user => <TableRow key={user.id} hover tabIndex={0} className="group-user-row" onClick={() => router.push(`/dashboard/users/${user.id}`)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') router.push(`/dashboard/users/${user.id}`); }}><TableCell><Typography fontSize={11} fontWeight={900}>{user.name}</Typography></TableCell><TableCell>{user.email}</TableCell><TableCell><Chip label={user.status} size="small" className="active-chip" /></TableCell><TableCell>{user.location}</TableCell><TableCell>{user.created}</TableCell></TableRow>)}</TableBody></Table></Box></Card></Stack>;
}

function metric(Icon: typeof EmailRounded, label: string, value: string) { return <Card className="group-metric" key={label}><Icon fontSize="small" /><Typography color="text.secondary" fontSize={10}>{label}</Typography><Typography fontSize={18} fontWeight={900}>{value}</Typography></Card>; }
function MetricRow({ value }: { value: string }) { const [label, amount] = value.split('|'); return <Stack direction="row" justifyContent="space-between" className="group-metric-row"><Typography fontSize={10}>{label}</Typography><Typography fontSize={10} fontWeight={900}>{amount}</Typography></Stack>; }
