'use client';

import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowBackRounded, EmailRounded, GroupsRounded, NotificationsActiveRounded, SearchRounded } from '@mui/icons-material';
import { Box, Button, Card, Chip, Grid, Skeleton, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { useActiveProject } from '@/hooks/projects/use-active-project';
import { lifecycleSegmentsApi } from '@/lib/projects/api';

export default function LifecycleSegmentWorkspace({ segmentId }: { segmentId: string }) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { active } = useActiveProject();
  const [query, setQuery] = useState('');
  const [cursor, setCursor] = useState<string | null>(null);
  const segmentQuery = useQuery({ queryKey: ['projects', 'lifecycle-segments', active?.id, segmentId], queryFn: () => lifecycleSegmentsApi.get(active!.id, segmentId), enabled: Boolean(active?.id) });
  const membersQuery = useQuery({ queryKey: ['projects', 'lifecycle-segments', active?.id, segmentId, 'members', cursor], queryFn: () => lifecycleSegmentsApi.members(active!.id, segmentId, { limit: 50, cursor }), enabled: Boolean(active?.id) });
  const segment = segmentQuery.data;
  const members = (membersQuery.data?.members ?? []).filter(user => `${user.externalUserId ?? ''} ${user.name ?? ''} ${user.email ?? ''}`.toLowerCase().includes(query.toLowerCase()));
  const users = segment?.userCount ?? segment?.usersCount ?? 0;
  return <Stack gap={2} className="audience-group-workspace">
    <Button startIcon={<ArrowBackRounded />} onClick={() => router.push(`/dashboard/users?tab=${searchParams.get('tab') || 'segments'}`)} className="group-back-button">Back to lifecycle segments</Button>
    <Card className="group-title-card"><Typography color="text.secondary" fontSize={10}>Lifecycle segment</Typography>{segmentQuery.isLoading ? <Skeleton width={220} /> : <><Typography variant="h3">{segment?.name ?? 'Lifecycle segment'}</Typography><Typography color="text.secondary" fontSize={11}>{segment?.description || 'Automatically updated based on user activity.'}</Typography></>}</Card>
    <Card className="group-section-card"><Typography variant="h3">Engagement</Typography><Typography color="text.secondary" fontSize={12}>Email and push performance for this lifecycle segment.</Typography><Grid container spacing={1.2} sx={{ mt: 1 }}>{metric(EmailRounded, 'Emails sent', '0')}{metric(EmailRounded, 'Emails opened', '0')}{metric(GroupsRounded, 'Users in segment', users.toLocaleString())}{metric(NotificationsActiveRounded, 'Pushes clicked', '0')}</Grid><Grid container spacing={1.5} sx={{ mt: 1 }}><Grid item xs={12} md={6}><Box className="group-engagement-panel"><Typography fontWeight={900}>Email engagement</Typography>{['Open rate|0%', 'Click rate|0%', 'Delivery rate|0%', 'Bounce rate|0%', 'Unsubscribe rate|0%', 'Spam complaint rate|0%'].map(row => <MetricRow key={row} value={row} />)}</Box></Grid><Grid item xs={12} md={6}><Box className="group-engagement-panel"><Typography fontWeight={900}>Push engagement</Typography>{['Sent|0', 'Delivered|0', 'Failed|0', 'Click rate|0%', 'No token|0%'].map(row => <MetricRow key={row} value={row} />)}</Box></Grid></Grid></Card>
    <Card className="group-section-card users-in-group"><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'center' }} gap={1}><Box><Typography variant="h3">Users in this segment</Typography><Typography color="text.secondary" fontSize={12}>{users.toLocaleString()} users</Typography></Box><TextField size="small" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search users by name or email" InputProps={{ startAdornment: <SearchRounded fontSize="small" sx={{ mr: 1, color: '#7c8aa2' }} /> }} /></Stack><Box sx={{ overflowX: 'auto', mt: 1.5 }}><Table size="small"><TableHead><TableRow>{['User', 'Email', 'Status', 'Location', 'Created'].map(label => <TableCell key={label}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{membersQuery.isLoading ? Array.from({ length: 6 }, (_, index) => <TableRow key={`segment-member-skeleton-${index}`}>{Array.from({ length: 5 }, (_, cell) => <TableCell key={cell}><Skeleton variant="text" /></TableCell>)}</TableRow>) : members.map(user => <TableRow key={user.id} hover tabIndex={0} className="group-user-row" onClick={() => router.push(`/dashboard/users/${user.id}?tab=segments`)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') router.push(`/dashboard/users/${user.id}?tab=segments`); }}><TableCell><Typography fontSize={11} fontWeight={900}>{user.name || user.externalUserId || user.id}</Typography></TableCell><TableCell>{user.email || '—'}</TableCell><TableCell><Chip label={user.accountStatus || 'Active'} size="small" className="active-chip" /></TableCell><TableCell>{user.country || '—'}</TableCell><TableCell>{user.createdAt && !Number.isNaN(Date.parse(user.createdAt)) ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(user.createdAt)) : '—'}</TableCell></TableRow>)}</TableBody></Table></Box><Stack direction="row" justifyContent="flex-end" gap={1} sx={{ mt: 1.5 }}><Button size="small" variant="outlined" disabled={!cursor || membersQuery.isFetching} onClick={() => setCursor(null)}>Previous</Button><Button size="small" variant="contained" disabled={!membersQuery.data?.nextCursor || membersQuery.isFetching} onClick={() => setCursor(membersQuery.data?.nextCursor ?? null)}>Next</Button></Stack></Card>
  </Stack>;
}

function metric(Icon: typeof EmailRounded, label: string, value: string) { return <Card className="group-metric" key={label}><Icon fontSize="small" /><Typography color="text.secondary" fontSize={10}>{label}</Typography><Typography fontSize={18} fontWeight={900}>{value}</Typography></Card>; }
function MetricRow({ value }: { value: string }) { const [label, amount] = value.split('|'); return <Stack direction="row" justifyContent="space-between" className="group-metric-row"><Typography fontSize={10}>{label}</Typography><Typography fontSize={10} fontWeight={900}>{amount}</Typography></Stack>; }
