'use client';

import { useState } from 'react';
import { CheckRounded, CloseRounded, LockRounded } from '@mui/icons-material';
import { Box, Button, Card, CardContent, Container, Dialog, DialogContent, DialogTitle, Divider, Grid, IconButton, Stack, TextField, Typography } from '@mui/material';
import { SiteShell, PageHero } from './SiteShell';

const plans = [
  { name: 'Free', price: '$0', detail: 'Forever', description: 'Explore the core retention workflow.', features: ['1,000 reachable users', '5,000 emails / month', '30,000 pushes / month', '1 active Journey', '100 AI Credits / month'] },
  { name: 'Starter', price: '$49', detail: 'per month', description: 'For early teams building their first lifecycle engine.', features: ['5,000 reachable users', '50,000 emails / month', '100,000 pushes / month', '5 active Journeys', '500 AI Credits / month'] },
  { name: 'Pro', price: '$249', detail: 'per month', description: 'For growing products with serious retention programs.', featured: true, features: ['25,000 reachable users', '250,000 emails / month', '500,000 pushes / month', '20 active Journeys', '2,000 AI Credits / month'] },
  { name: 'Enterprise', price: 'Custom', detail: 'tailored to your scale', description: 'For advanced teams with custom limits and support.', features: ['Custom reachable users', 'Custom channel volume', 'Advanced permissions', 'Dedicated success partner', 'Custom integrations'] },
];

export default function PricingExperience() { const [selected, setSelected] = useState<string | null>(null); return <SiteShell><PageHero eyebrow="PRICING" title="A plan that grows with your Project." description="Start with a clear, isolated Project. Upgrade when your reachable audience and retention program grow." /><Container maxWidth="lg" sx={{ py: { xs: 7, md: 11 } }}><Grid container spacing={2} alignItems="stretch">{plans.map(plan => <Grid item xs={12} sm={6} lg={3} key={plan.name}><Card className={plan.featured ? 'pricing-card featured' : 'pricing-card'} sx={{ height: '100%' }}>{plan.featured && <Box className="pricing-ribbon">RECOMMENDED</Box>}<CardContent sx={{ p: 3, pt: plan.featured ? 5 : 3, height: '100%', display: 'flex', flexDirection: 'column' }}><Typography fontWeight={900} fontSize={21}>{plan.name}</Typography><Typography color="text.secondary" fontSize={13} sx={{ minHeight: 58, mt: 1 }}>{plan.description}</Typography><Stack direction="row" alignItems="baseline" gap={.7} sx={{ mt: 2 }}><Typography fontSize={33} fontWeight={900}>{plan.price}</Typography><Typography color="text.secondary" fontSize={11}>{plan.detail}</Typography></Stack><Button variant={plan.featured ? 'contained' : 'outlined'} fullWidth onClick={() => setSelected(plan.name)} sx={{ mt: 2 }}>{plan.name === 'Enterprise' ? 'Talk to sales' : 'Start this plan'}</Button><Divider sx={{ my: 2.5 }} /><Stack gap={1.3}>{plan.features.map(feature => <Stack direction="row" gap={1} key={feature}><CheckRounded sx={{ color: plan.featured ? '#ff633f' : '#7231c9', fontSize: 17 }} /><Typography fontSize={12}>{feature}</Typography></Stack>)}</Stack></CardContent></Card></Grid>)}</Grid><Box className="pricing-note" sx={{ mt: 4 }}><LockRounded /><Box><Typography fontWeight={800}>Billing is Project-level</Typography><Typography color="text.secondary" fontSize={12}>Each Project has its own plan, usage, billing contact, invoices and payment method. Your Account can manage multiple Projects.</Typography></Box></Box></Container><Dialog open={Boolean(selected)} onClose={() => setSelected(null)} maxWidth="sm" fullWidth><DialogTitle>Start with {selected}<IconButton onClick={() => setSelected(null)} sx={{ position: 'absolute', right: 12, top: 12 }}><CloseRounded /></IconButton></DialogTitle><DialogContent><Typography color="text.secondary" fontSize={13}>Tell us where to send your Project setup link. No payment is required for this prototype.</Typography><Stack gap={2} sx={{ mt: 2 }}><TextField label="Work email" type="email" fullWidth /><TextField label="Project name" placeholder="e.g. PixlTrace" fullWidth /><Button variant="contained" size="large" href="/get-started">Continue to create account</Button></Stack></DialogContent></Dialog></SiteShell>; }
