'use client';

import { useState } from 'react';
import { AppBar, Box, Button, Container, Drawer, IconButton, Link, Paper, Stack, Toolbar, Typography } from '@mui/material';
import MenuRounded from '@mui/icons-material/MenuRounded';
import { SiteAccount, SiteAccountDrawer } from './SiteAccount';

const links = [['Product','/product'],['How It Works','/how-it-works'],['Use Cases','/use-cases'],['For Digital Products','/for-digital-products'],['Pricing','/pricing']];
const productGroups = [
  { title: 'Platform', items: [['Campaigns','Personalized email and push campaigns.','/product'],['Audiences','Build precise, reusable audience groups.','/product'],['Journey automations','Respond to user behavior in real time.','/product'],['Analytics','Measure the moments that matter.','/product']] },
  { title: 'AI features', items: [['Smart translations','Reach users in their preferred language.','/product'],['Customized journeys','Adapt messaging to user response.','/product'],['Journey analysis','See what to improve next.','/product']] },
];
const resourceGroups = [
  { title: 'Learn', items: [['Blog','Ideas for activation, retention and growth.','/blog'],['Customer case studies','See how digital products grow with PixlPush.','/customer-case-studies'],['Use cases','Explore journeys for every lifecycle moment.','/use-cases']] },
  { title: 'Explore', items: [['Why PixlPush','The thinking behind a better retention loop.','/why-pixlpush'],['ROI if switching','Build the business case for making a change.','/roi-if-switching'],['Glossary','Clear definitions for lifecycle marketing.','/glossary']] },
];
export function Logo() { return <Link href="/" aria-label="PixlPush home" underline="none" sx={{ display: 'inline-flex', alignItems: 'center' }}><Box component="img" src="/assets/logo.png" alt="PixlPush" sx={{ display: 'block', width: { xs: 135, sm: 155 }, height: 'auto' }} /></Link>; }
function MegaMenu({ kind }: { kind: 'product' | 'resources' }) { const groups = kind === 'product' ? productGroups : resourceGroups; return <Paper elevation={0} sx={{ position: 'absolute', top: 'calc(100% + 1px)', left: 0, right: 0, borderRadius: '0 0 24px 24px', border: '1px solid rgba(255,255,255,.12)', borderTop: 0, bgcolor: '#211331', color: '#fff', px: { md: 4, lg: 7 }, py: 4, boxShadow: '0 30px 70px rgba(43,15,65,.3)' }}><Box sx={{ display: 'grid', gridTemplateColumns: kind === 'product' ? '1fr 1fr 280px' : '1fr 1fr 280px', gap: 5, maxWidth: 1240, mx: 'auto' }}>{groups.map(group => <Box key={group.title}><Typography sx={{ color: '#ffab8e', fontWeight: 500, fontSize: 12, letterSpacing: '.12em', textTransform: 'uppercase', mb: 2 }}>{group.title}</Typography><Stack gap={1}>{group.items.map(([title, description, href]) => <Link key={title} href={href.replace('​​','')} underline="none" sx={{ p: 1.2, mx: -1.2, borderRadius: 2, color: 'rgba(255,255,255,.82)', '&:hover': { bgcolor: 'rgba(255,255,255,.08)' } }}><Typography fontWeight={600} fontSize={14}>{title}</Typography><Typography sx={{ color: 'rgba(255,255,255,.58)' }} fontSize={12} component="div" mt={.35}>{description}</Typography></Link>)}</Stack></Box>)}<Box sx={{ p: 2.3, borderRadius: 4, bgcolor: 'rgba(255,255,255,.08)', alignSelf: 'start' }}><Box sx={{ height: 116, borderRadius: 3, background: kind === 'product' ? 'linear-gradient(145deg,#ffb179,#8621c7)' : 'linear-gradient(145deg,#5620b9,#f26237)', mb: 2, p: 1.5 }}><Box sx={{ bgcolor: 'rgba(255,255,255,.9)', borderRadius: 2, height: '100%', p: 1 }}><Typography fontSize={11} fontWeight={500}>PIXLPUSH / {kind === 'product' ? 'JOURNEY BUILDER' : 'ANALYTICS'}</Typography><Box sx={{ mt: 1.5, height: 8, width: '72%', bgcolor: '#e5d4f0', borderRadius: 3 }} /><Box sx={{ mt: 1, height: 28, bgcolor: '#ffeadf', borderRadius: 2 }} /></Box></Box><Typography fontWeight={600}>{kind === 'product' ? 'See the platform in action' : 'Explore the resource room'}</Typography><Typography sx={{ color: 'rgba(255,255,255,.62)' }} fontSize={12} component="div" mt={.5} lineHeight={1.5}>{kind === 'product' ? 'Build a retention journey from signal to outcome.' : 'Practical ideas for teams building digital products.'}</Typography><Link href={kind === 'product' ? '/product' : '/resources'} sx={{ display: 'inline-block', mt: 1.5, color: '#ffab8e', fontWeight: 500, fontSize: 13 }}>Explore {kind === 'product' ? 'product' : 'resources'} →</Link></Box></Box></Paper>; }
export function SiteHeader() { const [open, setOpen] = useState(false); const [mega, setMega] = useState<'product' | 'resources' | null>(null); return <AppBar position="sticky" elevation={0} onMouseLeave={() => setMega(null)} sx={{ bgcolor: '#211331', backdropFilter: 'blur(18px)', color: '#fff', borderBottom: '1px solid rgba(255,255,255,.12)', zIndex: 10 }}><Toolbar sx={{ maxWidth: 1240, width: '100%', mx: 'auto', py: 1, justifyContent: 'space-between' }}><Logo /><Stack direction="row" gap={{ md: 2.2, lg: 3 }} sx={{ display: { xs: 'none', lg: 'flex' }, alignItems: 'center' }}>{[['Product','product'], ...links.slice(1).map(x => [x[0], x[1]]), ['Resources','resources']].map(([label, value]) => value === 'product' || value === 'resources' ? <Box key={label} onMouseEnter={() => setMega(value as 'product' | 'resources')} sx={{ py: 2, cursor: 'pointer' }}><Link href={value === 'product' ? '/product' : '/resources'} underline="none" sx={{ fontSize: 13, fontWeight: 500, color: mega === value ? '#ffab8e' : 'rgba(255,255,255,.82)' }}>{label} <span style={{ fontSize: 12 }}>{mega === value ? '⌃' : '⌄'}</span></Link></Box> : <Link key={label} href={value} underline="none" sx={{ fontSize: 13, fontWeight: 500, color: 'rgba(255,255,255,.82)', '&:hover': { color: '#ffab8e' } }}>{label}</Link>)}</Stack><Stack direction="row" gap={1} alignItems="center" justifyContent="flex-end" sx={{ display: { xs: 'none', sm: 'flex' }, minWidth: 216 }}><SiteAccount /></Stack><IconButton onClick={() => setOpen(true)} sx={{ display: { xs: 'flex', lg: 'none' }, color: '#fff' }}><MenuRounded /></IconButton></Toolbar>{mega && <Box sx={{ display: { xs: 'none', lg: 'block' } }} onMouseEnter={() => setMega(mega)}><MegaMenu kind={mega} /></Box>}<Drawer anchor="right" open={open} onClose={() => setOpen(false)} PaperProps={{ sx: { bgcolor: '#211331', color: '#fff' } }}><Stack sx={{ p: 3, width: 290, color: '#fff' }} gap={2.2}><Logo />{links.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} underline="none" fontWeight={500} sx={{ color: 'rgba(255,255,255,.84)' }}>{label}</Link>)}<Link href="/resources" onClick={() => setOpen(false)} underline="none" fontWeight={500} sx={{ color: 'rgba(255,255,255,.84)' }}>Resources</Link><SiteAccountDrawer onNavigate={() => setOpen(false)} /></Stack></Drawer></AppBar>; }
export function SiteFooter() { const columns = [{ title: 'Product', links: [['Platform','/product'],['How it works','/how-it-works'],['Use cases','/use-cases'],['For digital products','/for-digital-products'],['Pricing','/pricing']] }, { title: 'Resources', links: [['Blog','/blog'],['Customer case studies','/customer-case-studies'],['Glossary','/glossary'],['ROI if switching','/roi-if-switching'],['Resources hub','/resources']] }, { title: 'Company', links: [['Why PixlPush','/why-pixlpush'],['Contact sales','/get-started'],['Log in','/login'],['Create account','/get-started']] }]; return <Box component="footer" sx={{ bgcolor: '#211331', color: '#fff', position: 'relative', overflow: 'hidden' }}><Container maxWidth="lg" sx={{ py: { xs: 6, md: 8 } }}><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr 1fr', md: '1.6fr 1fr 1fr 1fr' }, gap: { xs: 4, md: 6 } }}><Box sx={{ gridColumn: { xs: '1 / -1', md: 'auto' } }}><Box component="img" src="/assets/logo.png" alt="PixlPush" sx={{ display: 'block', width: 165, height: 'auto' }} /><Typography color="rgba(255,255,255,.62)" fontSize={13} sx={{ mt: 1.5, maxWidth: 220, lineHeight: 1.6 }}>Behavior-aware journeys for digital products that want retention to compound.</Typography><Stack direction="row" gap={1} sx={{ mt: 2 }}><Box component="a" href="#" sx={{ width: 32, height: 32, borderRadius: '50%', display: 'grid', placeItems: 'center', color: '#fff', border: '1px solid rgba(255,255,255,.2)', textDecoration: 'none', fontSize: 12, fontWeight: 500 }}>in</Box><Box component="a" href="#" sx={{ width: 32, height: 32, borderRadius: '50%', display: 'grid', placeItems: 'center', color: '#fff', border: '1px solid rgba(255,255,255,.2)', textDecoration: 'none', fontSize: 14 }}>𝕏</Box></Stack></Box>{columns.map(column => <Box key={column.title}><Typography fontSize={11} fontWeight={500} letterSpacing=".14em" sx={{ color: '#ffab8e', textTransform: 'uppercase', mb: 2 }}>{column.title}</Typography><Stack gap={1.3}>{column.links.map(([label, href]) => <Link key={label} href={href} underline="none" sx={{ color: 'rgba(255,255,255,.68)', fontSize: 13, '&:hover': { color: '#fff' } }}>{label}</Link>)}</Stack></Box>)}</Box><Box sx={{ mt: 6, pt: 2.5, borderTop: '1px solid rgba(255,255,255,.14)', display: 'flex', flexWrap: 'wrap', gap: 2, justifyContent: 'space-between', color: 'rgba(255,255,255,.48)', fontSize: 12 }}><span>© 2025 PixlPush. All rights reserved.</span><Stack direction="row" gap={2}><Link href="#" underline="none" sx={{ color: 'inherit' }}>Privacy</Link><Link href="#" underline="none" sx={{ color: 'inherit' }}>Terms</Link><Link href="#" underline="none" sx={{ color: 'inherit' }}>Security</Link></Stack></Box></Container></Box>; }
export function SiteShell({ children }: { children: React.ReactNode }) { return <><SiteHeader />{children}<SiteFooter /></>; }
export function PageHero({ eyebrow, title, description, children, dark = false }: { eyebrow: string; title: string; description: string; children?: React.ReactNode; dark?: boolean }) { return <Box className="grain" sx={{ background: dark ? 'linear-gradient(135deg,#5517b8,#941b91 54%,#f3542e)' : 'linear-gradient(116deg,#ffd1e9 0%,#ffbd87 40%,#ff6d2d 100%)', color: dark ? '#fff' : '#32114d', py: { xs: 9, md: 13 } }}><Container maxWidth="lg"><Box sx={{ maxWidth: 780 }}><Typography variant="overline" sx={{ color: dark ? '#ffc8ad' : '#6417b9', fontWeight: 500, letterSpacing: '.14em' }}>{eyebrow}</Typography><Typography variant="h1" sx={{ fontSize: { xs: 48, md: 56 }, lineHeight: .96, mt: 1 }}>{title}</Typography><Typography sx={{ fontSize: { xs: 16, md: 20 }, lineHeight: 1.5, mt: 3, maxWidth: 620, color: dark ? 'rgba(255,255,255,.76)' : '#60385f' }}>{description}</Typography>{children && <Box sx={{ mt: 4 }}>{children}</Box>}</Box></Container></Box>; }
export function SectionIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) { return <Stack gap={1} sx={{ maxWidth: 720, mb: 5 }}><Typography variant="overline" color="secondary" fontWeight={500} letterSpacing=".14em">{eyebrow}</Typography><Typography variant="h2" sx={{ fontSize: { xs: 40, md: 56 }, lineHeight: 1 }}>{title}</Typography>{description && <Typography color="text.secondary" fontSize={16} lineHeight={1.6}>{description}</Typography>}</Stack>; }
